coverage:
  precision: 2
  round: nearest
  range: "40...70"
  ignore: 
    - "*/src/main/java/il/ac/technion/cs/smarthouse/applications/*"
    - "**/gui/**"
    - "System/**/system/dashboard/*"
    - "System/**/system/SystemFailureDetector.java"
    - "System/**/system/notification_center/*"
    - "System/**/developers_api/*"
    - "System/**/Entry.java"
    - "SensorsSimulator/**"
    - "Common/**/utils/JavaFxHelper.java"

