codecov:
  branch: master
  bot: null

coverage:
  precision: 2
  round: up
  range: "30...100"
  status:
    project:
      default:
        enabled: no
        target: auto
    changes: no

  ignore: 
    - src/main/java/il/ac/technion/cs/eldery/applications
    - src/main/java/il/ac/technion/cs/eldery/sensors/sos/gui
    - src/main/java/il/ac/technion/cs/eldery/sensors/stove/gui
    - src/main/java/il/ac/technion/cs/eldery/sensors/vitals/gui
    - src/main/java/il/ac/technion/cs/eldery/system/gui

# Don't post a comment on pull requests.
comment: off

comment:
  layout: "header, diff, changes, sunburst, uncovered, tree"
  branches: null
behavior: default