coverage:
  precision: 2
  round: nearest
  range: "40...70"
  ignore: 
    - "*/src/main/java/il/ac/technion/cs/smarthouse/applications/*"
    - "System/src/main/java/il/ac/technion/cs/smarthouse/sensors/*/gui/*"
    - "System/src/main/java/il/ac/technion/cs/smarthouse/system/gui/*"
