coverage:
  precision: 2
  round: nearest
  range: "40...70"
  ignore: 
    - "*/src/main/java/il/ac/technion/cs/smarthouse/applications/*"
    - "System/src/main/java/il/ac/technion/cs/smarthouse/sensors/*/gui/*"
    - "System/src/main/java/il/ac/technion/cs/smarthouse/system/gui/*"
    - "System/src/main/java/il/ac/technion/cs/smarthouse/mvp/*"
    - "System/src/main/java/il/ac/technion/cs/smarthouse/system/dashboard/*"
    - "System/src/main/java/il/ac/technion/cs/smarthouse/javafx_elements/*"
    - "System/src/main/java/il/ac/technion/cs/smarthouse/developers_api/*"
    - "System/src/main/java/il/ac/technion/cs/smarthouse/Entry.java"
    - "SensorsSimulator/**"
    - "Common/src/main/java/il/ac/technion/cs/smarthouse/utils/JavaFxHelper.java"

