coverage:
  precision: 2
  round: nearest
  range: "40...70"
  ignore: 
    - "*/src/main/java/il/ac/technion/cs/smarthouse/applications/*"
    - "Applications/ACU/src/main/java/il/ac/technion/cs/simulation/*"
    - "**/gui/**"
    - "System/**/dashboard/*"
    - "System/**/SystemFailureDetector.java"
    - "System/**/notification_center/*"
    - "System/**/developers_api/*"
    - "System/**/system_presenter/*"
    - "System/**/sensors/*"
    - "System/**/Entry.java"
    - "System/**/SystemSaver.java"
    - "System/**/SystemCore.java"
    - "SensorsSimulator/**"
    - "Common/**/utils/JavaFxHelper.java"
    - "Common/**/gui_controller/*"
    - "Common/**/sensors/*"
    - "ApplicationsIncludedHouse/**"

