codecov:
  branch: master
  bot: null

coverage:
  precision: 2
  round: up
  range: "30...100"
  status:
    project:
      default:
        enabled: no
        target: auto
    changes: no

# Don't post a comment on pull requests.
comment: off

paths:
  - src/main/java/il/ac/technion/cs/eldery/*
  - !src/main/java/il/ac/technion/cs/eldery/applications

comment:
  layout: "header, diff, changes, sunburst, uncovered, tree"
  branches: null
behavior: default